---
- hosts: prod-server
  become: azureuser
  become: true
  tasks:
    - name: deploy build to tomcat
      shell:  "http://20.212.18.14:8081/repository/projectoss-release/Demoapp/WebApp/1.1.1/WebApp-1.1.1.war" -O /home/azureuser/webapps
